### ISSUE TITLE
Trying to sign up breaks it

### ISSUE THREAD

**Issue by HariZaKitsukami** [mbgamer05/Constellation#3]
FYI there was nothing in either the username nor the password
### Stack trace
System.ArgumentException: Data Source cannot be empty.  Use :memory: to open an in-memory database
   at System.Data.SQLite.SQLiteConnection.Open()
   at Constellation.Form1.btnSend_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by mbgamer05** [comment]
this is a know error you need to restart the application, does this problem persist over?

**Comment by HariZaKitsukami** [comment]
It worked after restarting it
Something about creating a folder

**Comment by mbgamer05** [comment]
yeah currently investigating what is causing the error

**Comment by mbgamer05** [comment]
Issue Resolved
